### ISSUE TITLE
Simplify case_sensitive/case_insensitive flags for TOML

### ISSUE THREAD

**Issue by rw-access** [endgameinc/eql#34]
Based on some feedback, the tests should be simplified.

Every test _must_ specify `case_sensitive=true`, `case_insensitive=true` or both.

Currently, tests that support both do not specify, but this implicit behavior is a little backwards. Instead, we should always be explicit. Tests that work for both will look like:
```toml
case_sensitive = true
case_insensitive = true
```
